### ISSUE TITLE
2025 Bug Fixes

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#218]
So going into the new year I know you're probably gonna need a way to ease back in. This issue should act as a guide to help you get back into the flow. 

- [x] Allow Absorb to Stack  [Absorb sTack](https://github.com/MathiasGruber/TheNinjaRPG/issues/221)
- [x] #226
- [x] #247
- [x] Fix Friendly Fire Bugs: [Friendly Fire Issue ](https://github.com/MathiasGruber/TheNinjaRPG/issues/217)
- [x] Events are showing up for everyone on their profile even if they did not accept it, also Minimum and Maximum level requirement are not working for Events. 
- [x] Prevent Tags you need to do an action before the tag expires  [Prevent Issue Thread ](https://github.com/MathiasGruber/TheNinjaRPG/issues/199)
- [x] Ability for Players in profile settings, to set what offense is their highest and what Generals will be their highest. So the highest tags on jutsu will pull from this setting. 
- [x] Killing an AFK Player makes you stuck in combat [AFK Issue](https://github.com/MathiasGruber/TheNinjaRPG/issues/190)
- [x] Silence Doesn't Automatically clear after it ends [Silence Issue](https://github.com/MathiasGruber/TheNinjaRPG/issues/138)
- [x] While Traveling To Wake Island you can view the building and roll a Bloodline multiple time [Wake Island Issue](https://discord.com/channels/1080832341234159667/1307602792625606766) Note i think the simplest fix is that the player shouldn't be able to access the menu of where they are going until they get there. 
- [x]  Can Equip more than one Pierce Jutsu [Pierce Bug Thread](https://discord.com/channels/1080832341234159667/1314408199163609098)
- [x] Stealth does not allow you to basic heal. It should allow you to use basic heal. 
- [x] Map Bug [Map Bugs](https://github.com/MathiasGruber/TheNinjaRPG/issues/211)
- [x] Proceeds to Features Issue [Features Road Map](https://github.com/MathiasGruber/TheNinjaRPG/issues/219)

**Comment by MathiasGruber** [comment]
We need to split all these into separate well-defined github issues with as much information each as possible. 

It seems there is a big push towards creating AI that can resolve github issues, and I plan to have us at the forefront of using such technology. 

Initially, we will use Open Hands (https://github.com/All-Hands-AI/OpenHands) which can be started by adding the "fix-me" label to a given github issue, which will then prompt the AI to attempt to fix the issue in question and create a PR for me to review.

For this to work will, though, the AI needs as MUCH information and context about each issue as possible - it does not as such know of the game, so more is better.

**Comment by theeneon** [comment]
> We need to split all these into separate well-defined github issues with as much information each as possible.
> 
> It seems there is a big push towards creating AI that can resolve github issues, and I plan to have us at the forefront of using such technology.
> 
> Initially, we will use Open Hands (https://github.com/All-Hands-AI/OpenHands) which can be started by adding the "fix-me" label to a given github issue, which will then prompt the AI to attempt to fix the issue in question and create a PR for me to review.
> 
> For this to work will, though, the AI needs as MUCH information and context about each issue as possible - it does not as such know of the game, so more is better.

Yes, This is more of a guideline than the issue request. Will make independent issues for each and allow us to work on them separately this was more a plan of action for everyone else and us to keep track of stuff.
