### ISSUE TITLE
Features Road Map

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#219]
- [x] Complete Syndicate [Syndicate Issue](https://github.com/MathiasGruber/TheNinjaRPG/issues/150) 
- [x] War  System[War System Issues](https://github.com/MathiasGruber/TheNinjaRPG/issues/81)
- [ ] Quest Redesign [Quest Issue](https://github.com/MathiasGruber/TheNinjaRPG/issues/132)
- [x] Inventory Overhaul [Invetory Issues](https://github.com/MathiasGruber/TheNinjaRPG/issues/170)
- [ ] Battle Pyramid [Battle Pyramids](https://github.com/MathiasGruber/TheNinjaRPG/issues/137)
- [ ] Professions [Professions Issues](https://github.com/MathiasGruber/TheNinjaRPG/issues/163)
- [ ] Occupations Overhaul [Occupations Issues](https://github.com/MathiasGruber/TheNinjaRPG/issues/200)
- [x] New Tavern [Tavern Issues](https://github.com/MathiasGruber/TheNinjaRPG/issues/68)
- [ ] Skill Tree [Skill Tree Issues](https://github.com/MathiasGruber/TheNinjaRPG/issues/113)
- [ ] PVP Rank

After all of these are complete the only thing left is the new character selector and we can release.

**Comment by MathiasGruber** [comment]
Moved to roadmap: https://github.com/users/MathiasGruber/projects/3?query=sort%3Aupdated-desc+is%3Aopen
